### ISSUE TITLE
[Documentation] Could you provide copy/paste - pasteable commands to follow the steps necessary in the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [nervous-inhuman/tplink-tapo-c200-re#5]
Could you provide copy/paste - pasteable commands to follow the steps necessary in the main README?

I am having some trouble connecting to the C200 on linux via the commandline, so any help
would be great.

**Comment by DrmnSamoLiu** [comment]
If you are just trying to "use" instead of RE/Hacking your tapo camera,
then I will recommend take a look at pytapo project:
https://github.com/JurajNyiri/pytapo

There they have more support on how to access your tapo via cli :)

rubyFeedback ***@***.***> 於 2022年2月9日 週三 上午9:03 寫道：

**Comment by DrmnSamoLiu** [comment]
If you are just trying to "use" instead of RE/Hacking your tapo camera,
then I will recommend take a look at pytapo project:
https://github.com/JurajNyiri/pytapo

There they have more support on how to access your tapo via cli :)
